routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/dashboard');

Route::redirect('/home', '/dashboard');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('students', 'StudentsController')->middleware('auth');

Route::get('/users', 'UsersController@index')->name('users.index')->middleware('auth');

app/Student.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $guarded = ['id'];

    public function getAgeAttribute()
    {
        return Carbon::parse($this->date_of_birth)->age;
    }

    public function getFullnameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function getImagePathAttribute()
    {
        if ($this->image !== null) {
            return url('storage/images/' . $this->image);
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use App\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard', [
            'students' => Student::all()->count(),
            'users' => User::all()->count()
        ]);
    }
}

app/Http/Controllers/StudentsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreStudent;
use App\Http\Requests\UpdateStudent;
use App\Repositories\StudentRepositoryInterface;

class StudentsController extends Controller
{
    /**
     * @var StudentRepositoryInterface
     */
    private $student;

    /**
     * StudentsController constructor.
     * @param StudentRepositoryInterface $student
     */
    public function __construct(StudentRepositoryInterface $student)
    {
        $this->student = $student;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = $this->student->all();

        return view('students.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreStudent
     * @return \Illuminate\Http\Response
     * @throws
     */
    public function store(StoreStudent $request)
    {
        $attributes = $request->validated();

        $this->student->create($attributes);

        return back()->with('success', 'Student Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  $student
     * @return \Illuminate\Http\Response
     */
    public function show($student)
    {
        $student = $this->student->get($student);

        return view('students.show')->with(compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  $student
     * @return \Illuminate\Http\Response
     */
    public function edit($student)
    {
        $student = $this->student->get($student);

        return view('students.edit')->with(compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateStudent $request
     * @param  $student
     * @return \Illuminate\Http\Response
     * @throws
     */
    public function update(UpdateStudent $request, $student)
    {
        $attributes = $request->validated();

        $this->student->update($student, $attributes);

        return back()->with('success', 'Student Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  $student
     * @return \Illuminate\Http\Response
     * @throws
     */
    public function destroy($student)
    {
        $this->student->delete($student);

        return back()->with('success', 'Student Deleted');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::orderBy('id', 'DESC')->paginate(10);
        return view('users.index', compact('users'));
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@include('includes/styles')

@section('content')
    @include('includes/sidebar')

    <div class="container">
        <div class="row">
            <div class="col s12 m3">
                <div class="card z-depth-3 red darken-1 white-text">
                    <div class="card-content">
                        <div class="card-title center">Registered Students</div>
                        <div class="center">
                            <i class="material-icons large">people</i>
                        </div>
                        <div class="center">
                            <h5>{{$students}}</h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col s12 m3">
                <div class="card z-depth-3 purple darken-1 white-text">
                    <div class="card-content">
                        <div class="card-title center">Registered Users</div>
                        <div class="center">
                            <i class="material-icons large">supervised_user_circle</i>
                        </div>
                        <div class="center">
                            <h5>{{$users}}</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="fixed-action-btn">
        <a class="btn-floating btn-large waves-effect waves-light red pulse" href="{{ route('students.create') }}">
            <i class="large material-icons">add</i>
        </a>
    </div>
@endsection

resources/views/includes/styles.blade.php
@section('styles')
    <style>
        header, main, footer {
            padding-left: 300px !important;
        }

        @media only screen and (max-width : 992px) {
            header, main, footer {
                padding-left: 0 !important;
            }
        }
    </style>
@endsection

resources/views/students/create.blade.php
@extends('layouts.app')

@include('includes/styles')

@section('content')
    @include('includes/sidebar')
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h3 class="center">Student Registration</h3>
            </div>
        </div>
        @if (session('success'))
            <script>
                var message = @json(session('success'));
                document.addEventListener('DOMContentLoaded', function () {
                    window.M.toast({
                        html: message
                    })
                })
            </script>
        @endif

        <div class="card">
            <div class="card-content">
                <form action="{{ route('students.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf()

                    <div class="row">
                        <div class="input-field col s12 m6">
                            <label for="first_name">First Name</label>
                            <input type="text" id="first_name"
                                   class="@error('first_name') invalid @enderror"
                                   name="first_name" value="{{ old('first_name') }}">

                            @error('first_name')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="input-field col s12 m6">
                            <label for="last_name">Last Name</label>
                            <input id="last_name" type="text"
                                   class="@error('last_name') invalid @enderror"
                                   name="last_name" value="{{ old('last_name') }}">

                            @error('last_name')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6">
                            <label for="email">Email</label>
                            <input type="email" id="email"
                                   class="@error('email') invalid @enderror"
                                   name="email" value="{{ old('email') }}">

                            @error('email')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="input-field col s12 m6">
                            <label for="address">Address</label>
                            <textarea id="address"
                                      class="materialize-textarea @error('address') invalid @enderror"
                                      name="address">{{ old('address') }}</textarea>

                            @error('address')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6">
                            <label for="nic">NIC</label>
                            <input type="text" id="nic"
                                   class="@error('nic') invalid @enderror"
                                   name="nic" value="{{ old('nic') }}">

                            @error('nic')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="input-field col s12 m6">
                            <label for="passport">Passport No</label>
                            <input id="passport" type="text"
                                   class="@error('passport') invalid @enderror"
                                   name="passport" value="{{ old('passport') }}">

                            @error('passport')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6">
                            <label for="date_of_birth">Date of Birth</label>
                            <input type="text" id="date_of_birth"
                                   class="datepicker @error('date_of_birth') invalid @enderror"
                                   name="date_of_birth" value="{{ old('date_of_birth') }}">

                            @error('date_of_birth')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="input-field col s12 m6">
                            <label for="phone">Phone</label>
                            <input id="phone" type="number"
                                   class="@error('phone') invalid @enderror"
                                   name="phone" value="{{ old('phone') }}">

                            @error('phone')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6">
                        <span>
                            <label>
                                <input name="gender" type="radio" value="male" checked/>
                                <span>Male</span>
                            </label>
                        </span>
                            <span>
                            <label>
                                <input name="gender" type="radio" value="female"/>
                                <span>Female</span>
                            </label>
                        </span>

                            @error('gender')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="file-field input-field col s12 m6">
                            <div class="btn">
                                <span>File</span>
                                <input type="file" name="image">
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>

                            @error('image')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <button class="btn waves-effect waves-light block-on-small-and-down mb-1" type="submit"
                            name="action">
                        Submit
                        <i class="material-icons right">send</i>
                    </button>
                    <button class="btn waves-effect waves-light block-on-small-and-down mb-1" type="reset">
                        Clear
                        <i class="material-icons right">clear</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@include('includes/styles')

@section('content')
    @include('includes/sidebar')
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h3 class="center">Edit Student - {{ $student->id }}</h3>
            </div>
        </div>
        @if (session('success'))
            <script>
                var message = @json(session('success'));
                document.addEventListener('DOMContentLoaded', function () {
                    window.M.toast({
                        html: message
                    })
                })
            </script>
        @endif

        <div class="card">
            <div class="card-content">
                @if($student->image !== null)
                    <div class="row">
                        <div class="col s12 m6 offset-m3">
                            <img class="materialboxed responsive-img" src="{{$student->image_path}}"
                                 alt="{{ $student->full_name }}">
                        </div>
                    </div>
                @endif
                <form action="{{ route('students.update', $student->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf()
                    @method('PATCH')

                    <div class="row">
                        <div class="input-field col s12 m6">
                            <label for="first_name">First Name</label>
                            <input type="text" id="first_name"
                                   class="@error('first_name') invalid @enderror"
                                   name="first_name" value="{{ old('first_name') ?? $student->first_name }}">

                            @error('first_name')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="input-field col s12 m6">
                            <label for="last_name">Last Name</label>
                            <input id="last_name" type="text"
                                   class="@error('last_name') invalid @enderror"
                                   name="last_name" value="{{ old('last_name') ?? $student->last_name }}">

                            @error('last_name')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6">
                            <label for="email">Email</label>
                            <input type="email" id="email"
                                   class="@error('email') invalid @enderror"
                                   name="email" value="{{ old('email') ?? $student->email }}">

                            @error('email')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="input-field col s12 m6">
                            <label for="address">Address</label>
                            <textarea id="address"
                                      class="materialize-textarea @error('address') invalid @enderror"
                                      name="address">{{ old('address') ?? $student->address }}</textarea>

                            @error('address')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6">
                            <label for="nic">NIC</label>
                            <input type="text" id="nic"
                                   class="@error('nic') invalid @enderror"
                                   name="nic" value="{{ old('nic') ?? $student->nic }}">

                            @error('nic')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="input-field col s12 m6">
                            <label for="passport">Passport No</label>
                            <input id="passport" type="text"
                                   class="@error('passport') invalid @enderror"
                                   name="passport" value="{{ old('passport') ?? $student->passport }}">

                            @error('passport')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6">
                            <label for="date_of_birth">Date of Birth</label>
                            <input type="text" id="date_of_birth"
                                   class="datepicker @error('date_of_birth') invalid @enderror"
                                   name="date_of_birth" value="{{ old('date_of_birth') ?? $student->date_of_birth }}">

                            @error('date_of_birth')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="input-field col s12 m6">
                            <label for="phone">Phone</label>
                            <input id="phone" type="number"
                                   class="@error('phone') invalid @enderror"
                                   name="phone" value="{{ old('phone') ?? $student->phone }}">

                            @error('phone')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m6">
                        <span>
                            <label>
                                <input name="gender" type="radio" value="male" {{ $student->gender == 'male' ? 'checked' : '' }} />
                                <span>Male</span>
                            </label>
                        </span>
                            <span>
                            <label>
                                <input name="gender" type="radio" value="female" {{ $student->gender == 'female' ? 'checked' : '' }} />
                                <span>Female</span>
                            </label>
                        </span>

                            @error('gender')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="file-field input-field col s12 m6">
                            <div class="btn">
                                <span>File</span>
                                <input type="file" name="image">
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>

                            @error('image')
                            <span class="helper-text red-text">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <button class="btn waves-effect waves-light block-on-small-and-down mb-1 orange lighten-1"
                            type="submit"
                            name="action">
                        Update
                        <i class="material-icons right">edit</i>
                    </button>
                    <button class="btn waves-effect waves-light block-on-small-and-down mb-1" type="reset">
                        Clear
                        <i class="material-icons right">clear</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@include('includes/styles')

@section('content')
    @include('includes/sidebar')

    <h3 class="center">Students</h3>
    <hr>
    @if (session('success'))
        <script>
            var message = @json(session('success'));
            document.addEventListener('DOMContentLoaded', function () {
                window.M.toast({
                    html: message
                })
            })
        </script>
    @endif

    <table class="striped highlight centered responsive-table mb-1">
        <thead>
        <tr>
            <th width="100">ID</th>
            <th>Fullname</th>
            <th>Email</th>
            <th>Address</th>
            <th>Nic</th>
            <th>Passport</th>
            <th>DOB</th>
            <th>Age</th>
            <th>Phone</th>
            <th>Gender</th>
            <th width="150" class="center">Actions</th>
        </tr>
        </thead>

        <tbody>
        @forelse ($students as $student)
            <tr>
                <td>{{ $student->id }}</td>
                <td>{{ $student->fullname }}</td>
                <td>{{ $student->email }}</td>
                <td>{{ $student->address }}</td>
                <td>{{ $student->nic }}</td>
                <td>{{ $student->passport }}</td>
                <td>{{ $student->date_of_birth }}</td>
                <td>{{ $student->age }}</td>
                <td>{{ $student->phone }}</td>
                <td style="text-transform: capitalize">{{ $student->gender }}</td>
                <td>
                    <a class="btn-floating btn-small blue waves-effect waves-light tooltipped"
                       data-position="top" data-tooltip="View"
                       href="{{ route('students.show', $student->id) }}"><i class="material-icons">visibility</i></a>
                    <a class="btn-floating btn-small orange waves-effect waves-light tooltipped"
                       data-position="top" data-tooltip="Edit"
                       href="{{ route('students.edit', $student->id) }}"><i class="material-icons">edit</i></a>
                    <form action="{{ route('students.destroy', $student->id) }}" method="POST"
                          style="display: inline-block;">
                        @csrf
                        @method('DELETE')
                        <button class="btn-floating btn-small red waves-effect waves-light tooltipped"
                                data-position="left" data-tooltip="Delete" type="submit">
                            <i class="material-icons">delete</i></button>
                    </form>
                </td>
            </tr>
        @empty
            <tr>
                <td>No students</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    {{$students->links()}}
@endsection

resources/views/students/show.blade.php
@extends('layouts.app')

@include('includes/styles')

@section('content')
    @include('includes/sidebar')
    <div class="container">
        <h3 class="center">Student ID - {{ $student->id }}</h3>
        <div class="card">
            <div class="card-content">
                @if($student->image !== null)
                    <div class="row">
                        <div class="col s12 m6 offset-m3">
                            <img class="materialboxed responsive-img" src="{{$student->image_path}}"
                                 alt="{{ $student->full_name }}">
                        </div>
                    </div>
                @endif
                <div class="row">
                    <div class="input-field col s12 m6">
                        <label for="first_name">First Name</label>
                        <input type="text" id="first_name"
                               name="first_name" value="{{ $student->first_name }}" disabled>
                    </div>
                    <div class="input-field col s12 m6">
                        <label for="last_name">Last Name</label>
                        <input id="last_name" type="text"
                               name="last_name" value="{{ $student->last_name }}" disabled>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m6">
                        <label for="email">Email</label>
                        <input type="email" id="email"
                               name="email" value="{{ $student->email }}" disabled>
                    </div>
                    <div class="input-field col s12 m6">
                        <label for="address">Address</label>
                        <textarea id="address"
                                  class="materialize-textarea"
                                  name="address" disabled>{{ $student->address }}</textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m6">
                        <label for="nic">NIC</label>
                        <input type="text" id="nic"
                               name="nic" value="{{ $student->nic }}" disabled>
                    </div>
                    <div class="input-field col s12 m6">
                        <label for="passport">Passport No</label>
                        <input id="passport" type="text"
                               name="passport" value="{{ $student->passport }}" disabled>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m6">
                        <label for="date_of_birth">Date of Birth</label>
                        <input type="text" id="date_of_birth"
                               class="datepicker"
                               name="date_of_birth" value="{{ $student->date_of_birth }}" disabled>
                    </div>
                    <div class="input-field col s12 m6">
                        <label for="phone">Phone</label>
                        <input id="phone" type="text"
                               name="phone" value="{{ $student->phone }}" disabled>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m6">
                        <span>
                            <label>
                                <input name="gender" type="radio" {{ $student->gender == 'male' ? 'checked' : '' }} disabled/>
                                <span>Male</span>
                            </label>
                        </span>
                                    <span>
                            <label>
                                <input name="gender" type="radio" {{ $student->gender == 'female' ? 'checked' : '' }} disabled/>
                                <span>Female</span>
                            </label>
                        </span>
                    </div>
                    <div class="input-field col s12 m6">
                        <label for="age">Age</label>
                        <input type="text" id="age"
                               class="datepicker"
                               name="age" value="{{ $student->age }}" disabled>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection